hashicorp/nomad-autoscaler

docs/README.md
New:  ../demo/vagrant/README.md
Old:  ../demo/README.md
=> Fix broken link to Vagrant demo

go.mod, go.sum, plugins/nomad/target/tgcount.go, strategy/action.go
=> update Nomad to v0.11.0-beta2

policystorage/nomad.go
=> policy: fix assignment when dealing with empty policy target.

demo/vagrant/Vagrantfile
* Expose webapp port
* Remove unused Grafana port
* Update Nomad binary to 0.11.1
=> demo: expose webapp port and update Nomad binary version

command/agent.go
Any error when reading the agent config would result in the error
prefixed with "Error parsing command arguments" which can be
confusing if the error is because a config file cannot be found on
disk. This changes therefore makes the output more accurate and
easier to understand.
=> agent: improve command error output message and format.

demo/vagrant/Vagrantfile, go.mod, go.sum, plugins/builtin/target/nomad/plugin/state.go, plugins/builtin/target/nomad/plugin/state_test.go
=> Update Nomad dependancy to 0.11.2

agent/config/config.go, agent/config/config_test.go, agent/plugins_test.go
=> agent: configure target-strategy plugin for automatic launching.

plugins/builtin/target/aws-asg/plugin/aws.go, plugins/builtin/target/aws-asg/plugin/plugin.go
Changes a couple of log lines to provide a better operator
experience as well as fixes some behaviour based on initial
testing.
=> plugin/aws-asg: change log levels and small fixes.

policy/worker.go
A policy worker handler can exit due to a number of reasons but
the policy handler will always attempt to send to the proceedCh.
In the event where the worker has already exited, there is no
channel reciever which means the send to the channel blocks
endlessly.
=> policy: fix deadlock in eval worker when handler has exited.

demo/remote/README.md, demo/remote/aws.md, demo/remote/aws_autoscaler.nomad, demo/remote/packer/aws-packer.pkr.hcl, demo/remote/terraform/env/aws/terraform.tfvars.sample
=> Cluster scaling demo review

CHANGELOG.md, plugins/manager/manager.go, plugins/manager/util.go, plugins/manager/util_test.go
Not sure what I was thinking when I wrote this portion of the manager code.
closes #222
=> plugins: fix issue launching multiple plugins using the same driver

.circleci/config.yml, .circleci/config/config.yml
=> deps: update CircleCI used Golang version to 1.14.6.

demo/remote/terraform/env/aws/provider.tf, demo/remote/terraform/modules/aws-hashistack/provider.tf
=> demo/remote: fix aws-hashistack module provider region setup.

GNUmakefile
This brings the check inline with the update to Nomad as well as
provides better coverage.
=> build: add go.sum to make target check alongside go.mod.

GNUmakefile
Adding a make target for datadog plugin build
=> Datadog plugin build make target

.circleci/config.yml, .circleci/config/commands/install-go.yml
These commands were failing although not impacting the CI
process but should be removed.
=> build: remove sudo cmds from CircleCI config which were failing.

demo/vagrant/Vagrantfile
Also applying patch for currently borked upstream vagrant box. fixes #270
=> switching to focal and upstream package of hey

CHANGELOG.md
Consistency with Nomad and within the CHANGELOG.md itself.
=> changelog: capitalise sentence start across all entries.

sdk/eval.go, sdk/eval_test.go
this supports looking up policy associated with scaling actions
=> put the policy id in the scaling action metadata

GNUmakefile, agent/http/server.go, plugins/builtin/apm/datadog/plugin/plugin.go, plugins/builtin/apm/prometheus/plugin/plugin.go, plugins/builtin/target/aws-asg/plugin/aws.go, plugins/builtin/target/aws-asg/plugin/plugin.go, plugins/builtin/target/azure-vmss/plugin/azure.go, plugins/builtin/target/nomad/plugin/plugin.go, policy/nomad/parser.go, policy/nomad/validate.go, policyeval/broker_test.go, sdk/helper/uuid/uuid_test.go, tools/go.mod, tools/tools.go
Adds staticcheck to the tools make target and fixes all found issues.
=> build: use staticcheck to perform code analysis locally and in CI

policyeval/base_worker.go
=> check for nil action to avoid panic

demo/remote/aws_autoscaler.nomad
=> add example of datadog usage to the demo nomad job file

GNUmakefile, tools/go.mod, tools/go.sum, tools/tools.go
=> test: add hclogvet to check make target and tools install.

CHANGELOG.md
@cgbaker 
fix the word salad 😄
=> fix the word salad

CHANGELOG.md
Doc PR: https://github.com/hashicorp/nomad/pull/9908
Closes #359.
=> add CHANGELOG entry for #356

demo/vagrant/horizontal-app-scaling/jobs/autoscaler.nomad
specify job type explicitly for calrification
=> specify job type explicitly

demo/remote/azure/terraform/control/.terraform.lock.hcl, demo/remote/azure/terraform/control/main.tf, demo/remote/azure/terraform/modules/azure-hashistack/provider.tf, demo/remote/azure/terraform/modules/azure-hashistack/templates/azure_autoscaler.nomad
- Fix path to shared TF module
- Update Autoscaler jobspec to Nomad 1.0
- Move provider definition and version constraint to main module
=> demo/azure: update and fix Azure demo

demo/remote/README.md, demo/remote/gcp/README.md, demo/remote/gcp/packer/gcp-packer.pkr.hcl, demo/remote/gcp/terraform/.gitignore, demo/remote/gcp/terraform/control/.terraform.lock.hcl, demo/remote/gcp/terraform/control/main.tf, demo/remote/gcp/terraform/control/output.tf, demo/remote/gcp/terraform/control/terraform.tfvars.sample, demo/remote/gcp/terraform/control/variables.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/address.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/autoscaler.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/firewall.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/image.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/instance_group.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/lb.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/locals.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/network.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/output.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/project.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/provider.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/templates/gcp_autoscaler.nomad.tpl, demo/remote/gcp/terraform/modules/gcp-hashistack/templates/user-data-client.sh, demo/remote/gcp/terraform/modules/gcp-hashistack/templates/user-data-server.sh, demo/remote/gcp/terraform/modules/gcp-hashistack/variables.tf, demo/remote/gcp/terraform/modules/gcp-hashistack/vm.tf, demo/remote/shared/packer/config/99-default.dnsmasq.gcp, demo/remote/shared/packer/config/consul_gcp.service
Co-authored-by: Luiz Aoqui <luiz@hashicorp.com>
=> demo/remote: add GCP Managed Instance group demo.

command/agent.go
=> agent: fix issue causing incorrect debug/prom HTTP server config.

command/agent_test.go
Loading `DefaultEntConfig` allows for the test to work on OSS and ENT test suite.
=> Load ENT defaults in commant/agent_test.go

go.mod, go.sum, plugins/test/noop-apm/go.mod, plugins/test/noop-apm/go.sum, plugins/test/noop-strategy/go.mod, plugins/test/noop-strategy/go.sum, plugins/test/noop-target/go.mod, plugins/test/noop-target/go.sum
Uses commit: 149b150fb2d87766b8462346d68b72831f622047
=> deps: ensure Nomad 1.0.4 API dep.

GNUmakefile, plugins/builtin/strategy/threshold/main.go, plugins/builtin/strategy/threshold/plugin/plugin.go, plugins/builtin/strategy/threshold/plugin/plugin_test.go, plugins/manager/internal.go, plugins/plugin.go
Closes #438 
Should be merged after #484 to avoid a panic.
=> threshold strategy plugin

CHANGELOG.md
also updated the link to use the pull request
=> changelog: highlight threshold strategy

plugins/builtin/target/nomad/plugin/plugin_test.go, plugins/builtin/target/nomad/plugin/state_test.go
Not sure how this has been marked as passing 🤔
Seems like builtin plugin tests [are being ignored in CI](https://app.circleci.com/pipelines/github/hashicorp/nomad-autoscaler/1260/workflows/6398d155-194c-438c-9fd5-dca887b62c16/jobs/4303?invite=true#step-103-156)?
=> fix nomad target plugin test

CHANGELOG.md, plugins/builtin/target/nomad/plugin/plugin.go
=> Reload nomad client on status handlers 

.github/CODEOWNERS, .github/workflows/build.yml
=> build: remove deprecated set-output command from GHA

.release/ci.hcl
This replaces the explicit configuration enumerating each step in the common release tooling process with a single step that encapsulates all organizational requirements (signing, notarization, etc.).
=> Migrate CRT configuration to 'prepare' workflow

plugins/builtin/apm/prometheus/plugin/plugin.go, plugins/builtin/apm/prometheus/plugin/prometheus_test.go, plugins/builtin/target/aws-asg/plugin/retry.go, plugins/builtin/target/gce-mig/plugin/gce.go
Replace last usage of deprecated io/ioutil package.
=> Replace deprecated ioutil.

.copywrite.hcl
Once this is merged, I will raise an enterprise followup.
=> ci: add copywrite config file to manage exceptions.

command/agent.go
This addition also changes the way in which this config detail is logged, so that we better handle JSON logging.
=> agent: add HA enabled option to log config output.

plugins/shared/util.go, plugins/target/client.go, policy/policy.go
Fixes #644
Sorry for the delay on this. I've been busy with other things and then I forgot.
@lgfa29 Should I also add the timeout to the scale action?
=> Add timeout to scale action

.github/dependabot.yml
I think this works? We'll see next week 😅
=> ci: ignore dependabot updates for AWS

CHANGELOG.md, plugins/builtin/strategy/pass-through/plugin/plugin.go, plugins/builtin/strategy/pass-through/plugin/plugin_test.go
This is similar to a4e70bcdba.
=> add max_scale_up and max_scale_down for pass-through

.github/workflows/build.yml, Dockerfile, GNUmakefile
- **Add license to make zip target**
- **Add license inside Docker image; update labels**
- **Add license to packages**
=> Add LICENSE to build artifacts

.github/CODEOWNERS, CODEOWNERS
Setting a default for codeowners file for PLAT-3161
=> setting default codeowners file

.golangci.yml, plugins/builtin/target/gce-mig/plugin/retry.go, plugins/shared/util.go, plugins/shared/util_test.go, policyeval/broker_test.go
And update the codebase to pass the linter
=> Migrate the golanci-lint config file

.release/security-scan.hcl
Triaging false positive alert from the security scanner. Updated to use alpine_security.
=> ci: triage false scanner alerts
