hashicorp/nomad-autoscaler

GNUmakefile
docs/cli/README.md

The Makefile build target was not populating the version git vars
which meant the version command was missing some information. This
change ensures the makefile build target populates to the ldflags
to reflect those used during the release process.

build: populate version git vars when building using Makefile.

---

agent/agent.go
plugins/nomad/target/tgcount.go
plugins/target-value/strategy/targetvalue.go
strategy/action.go
strategy/strategy.go

If a Strategy passes a `nil` value in an Action, this indicates to the Autoscaler and Targets that the current count value shouldn't change.
This can be used to register events against the Target without executing any action.
Closes #41.

Allow `nil` value for Count

---

plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go

It is possible that the count of a task group we wish to scale is
0. It is also possible that the target the operator wishes the
metric maintain is zero. An example here would be a build system
queue, where the number of agents can scale to 0 if there is no
work to process. If work is added to the queue, the strategy is
to scale the build agents so that the queue metric is reduced to
the target of 0 items.
closes #76

plugins: allow target-value to handle zero count and target params

---

plugins/apm/apm.go
plugins/base/base.go
plugins/builtin/apm/nomad/main.go
plugins/builtin/apm/nomad/plugin/plugin.go
plugins/builtin/apm/prometheus/main.go
plugins/builtin/apm/prometheus/plugin/plugin.go
plugins/builtin/strategy/target-value/main.go
plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go
plugins/builtin/target/nomad/main.go
plugins/builtin/target/nomad/plugin/plugin.go
plugins/manager/manager.go
plugins/plugin.go
plugins/strategy/strategy.go
plugins/target/target.go

The UX for developing external plugins was OK, but required some
knowledge of the go-plugin library in order to correctly setup
and serve the plugin. This change aims to lower the barrier to
entry on writing plugins by making the required code simpler and
also mimicking the Nomad plugin interface.
PluginInfo has been moved into the base package as part of this
work. This seems a better logic location for the definition as it
is the response object of a defined interface function inside this
package.

plugins: improve external plugin development UX and mimic Nomad.

---

README.md

I was wondering if I should add more details about the nightly builds, but I thought it was not necessary. Any thoughts?

Add reference to nightly builds in README

---

.gitignore
go.mod
policystorage/nomad.go
policystorage/nomad_test.go

resolves #94 
policy was nobly trying to validate additional errors after discovery that "strategy" was of the wrong type (or, in the case of #94, did not exist). early return from this case.

policy validation: don't try so hard

---

agent/config/config_test.go

The ordering of plugin slices within the config is not important
but the assert.Equal method will fail is two slices to not match
with the same order. The test has been updated to reflect that
we do not need ordered plugin config slices.

agent: fix test flake within agent/config Merge test.

---

.circleci/config.yml
.circleci/config/jobs/check-deps-go.yml
.circleci/config/workflows/ci.yml
GNUmakefile

It is fairly easy for the go.mod file to become cluttered with
unrequired dependancies. This makefile addition therefore runs the
go mod command and checks if the go.mod file has changed as a
result to ensure this is caught during CI.
The target runs after the build phase as this also allows us to
catch dependancies that have not been added to the go.mod file
which are needed. This likely wont be hit during CircleCI runs,
but could be helpful for the development cycle.

build: add makefie target to check go.mod status.

---

plugins/builtin/apm/prometheus/plugin/plugin.go

When setting the configuration on the Prometheus APM plugin, it is
not required to pass the address config param. When the plugin
performs a query, it will error as the SDK does not add any
default address and so the HTTP call uses an address of "". This
change therefore suggests returning an error if the user specified
address is empty at the set config phase. This will provide
quicker user feedback on an error which will always occur
eventually.

prometheus: set config should error if address is not set.

---

plugins/manager/manager.go

When launching internal plugins, the named logger was being set
to the same value on all plugins. This makes it hard to understand
the logs of internal plugins. Adding the plugin name to the logger
helps differentiate.

plugin: add the plugin name to the logger when launching internal.

---

agent/agent.go

This PR prevents the Autoscaler from taking an action when count value doesn't change to avoid unnecessary work.

skip action when count doesn't change

---

plugins/strategy/action.go
plugins/strategy/action_test.go

Adds tests to the strategy Action set of functions. The tests
uncovered a bug and lint enhancement which are fixed within this
commit.
The lint enhancement changes the PushReason function to be
un-exported as it is currently only used within the strategy pkg.
The bug occured where a reason was added to the action in
situations where no reason previously existed. The meta reason
history was appended to from the empty reason string, before the
reason string was subsequently set.

plugin: add tests to strategy action.

---

plugins/builtin/apm/nomad/plugin/metrics.go
plugins/builtin/apm/nomad/plugin/metrics_test.go
policy/nomad/parser.go

Moving the query parsing logic to the Nomad APM plugin keeps it closer to where it actually is used.

Move nomad query parsing

---

policy/nomad/validate.go
policy/nomad/validate_test.go

This PR improves policy validation in a few ways:
1. **validate the right target component**: the initial implementation only validated `ScalingPolicy.Target` which is a `map[string]string` and doesn't actually need validation.
2. **encapsulate the logic to validate an HCL block in a function**: this allows us to re-use the validation logic in different places, such as `strategy` and `target`.
3. **return error messages related to the jobspec when possible**: previously the error messages would be related to the specific internal structure of the policy, which is not significant to end users. New error messages use the same `block1->block2` notation from the Nomad docs.
4. **only test `validateScalingPolicy`**: this is the main function that calls all the others. Testing individual …

Improve policy validation

---

CHANGELOG.md
agent/agent.go
agent/config/config.go
agent/config/config_test.go
command/agent.go
docs/agent/README.md
policy/nomad/parser.go
policy/nomad/parser_test.go
policy/nomad/source.go
policy/nomad/source_test.go
policy/nomad/testing.go
policy/source.go

This PR makes the logic that parses a policy from Nomad into the internal policy representation the Autoscaler uses.
The new parser makes a few assumptions:
1. `scaling->policy->evaluation_interval` defaults to the value of ~`scan_interval`~ `default_evaluation_time` from the agent config file.
2. the final `Policy.Target.Config` map has the values from `scaling->policy->target->config` (which are defined in the jobspec) merged with the values from `api.ScalingPolicy.Target` (which are predefined by the Nomad API as the group, job and namespace that has the `scaling` stanza). Values in the jobspec have higher priority.
3. the values of 'Job' and 'Group' from `api.ScalingPolicy.Target` are copied over to `Policy.Target.Config` as `job_id` and `group` if they are present yet (i.e., if the …

Refactor Nomad policy parsing and add tests

---

policy/handler.go
policy/manager.go
policy/nomad/source.go
policy/nomad/validate.go

Policy validation uses `multierror` to potentially return multiple error messages depending on how many fields are incorrect. 
The default formatter for `multierror` generates a string that is not ideal for structured log libraries, such as `hclog`:
```
2020-05-04T15:33:01.798-0400 [ERROR] policy_handler.policy_handler: invalid policy: 2 errors occurred:
* scaling->policy->query is missing
* scaling->policy->strategy->name is missing
: policy_id=eec161ee-c8f0-d998-2b3f-12a84d6083d2
```
```json
{
"@level":"error",
"@message":"invalid policy: 2 errors occurred:\n\t* scaling-\u003epolicy-\u003equery is missing\n\t* scaling-\u003epolicy-\u003estrategy-\u003ename is missing\n\n",
"@module":"policy_handler.policy_handler",
"@timestamp":"2020-05-04T15:36:14.313933-04:00", …
```

Improve validation log

---

plugins/builtin/target/nomad/plugin/plugin.go
policy/nomad/parser.go
policy/nomad/parser_test.go
policy/nomad/source.go
policy/nomad/source_test.go

When parsing a scaling policy from Nomad which did not contain a
target block within the policy map, the outer target map which
contained both the job and group information was ignored. This
resulted in evaluation failures and rendered the policy incapable
of being used by the autoscaler.
The fix updates the target parsing to correctly handle the above
described situation. Whilst also figuring this out, it made sense
to remove the unnecessary additional target mapping within
canonicalizePolicy() as pointed out in comments by @lgfa29. This
requires a small change to the Nomad target plugin, but results in
a simpler workflow.

policy: fix Nomad target parsing when target block is empty.

---

policy/nomad/source.go

Small change to remove disabled policies from the list of IDs being monitored. This allows stopping unnecessary policy evaluations earlier and from outside the individual policy handler.

Skip disabled policies when monitoring policy list from Nomad

---

agent/agent.go
agent/config/config.go
agent/config/config_test.go
command/agent.go
plugins/builtin/target/nomad/plugin/state.go
plugins/builtin/target/nomad/plugin/state_test.go
plugins/manager/manager.go
plugins/target/target.go
policy/handler.go
policy/handler_test.go
policy/manager.go
policy/nomad/parser.go
policy/nomad/parser_test.go
policy/nomad/source.go
policy/nomad/source_test.go
policy/nomad/validate.go
policy/nomad/validate_test.go
policy/policy.go

Cooldown is now supported within a scaling policy as a time
duration. If the scaling policy omits the cooldown field, a
default value will be used. The default value can be controlled
by the CLI and has a default value of 5mins.
In the event the agent successfully registers a scaling action,
the policy manager will be instructed to place the policy eval
handler in cooldown by updating the ticker to the cooldown time
duration. The ticker is reset to its eval time duration on the
first tick out of cooldown.
Target plugins can optionally return a meta entry to detail the
last scaling event from their prespective. This allows the
autoscaler to enforce cooldowns, even when scaling actions have
been triggered manually by operators. The flow is similar to that
mentioned above, the only …

agent: support scaling cooldowns to aid oscillation migration.

---

agent/agent.go
plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go
plugins/builtin/target/nomad/plugin/plugin.go
plugins/strategy/action.go
plugins/strategy/action_test.go

The way in which stdlib encoding/gob works means a pointer to a
types default value will result in the RPC translation becoming
nil. This meant external strategy plugins were not able to suggest
scaling to zero, as the pointer to zero would be translated to nil
which inturn is classed as dry-run.
This change removes the use of a pointer for count within strategy
action struct. Allowing the use of zero to indicate scaling to
zero. Dry run situations use a special -1 count field, to indicate
a dry run workflow should be triggered.
closes #83

plugin: fix bug in ext. strategy plugins suggesting scale to zero.

---

main.go

cli: always use cli exit code when exiting main function.

---

plugins/builtin/apm/nomad/plugin/metrics.go
plugins/builtin/apm/nomad/plugin/metrics_test.go

The Nomad APM used to /v1/metrics endpoint to gather task group
metric data. The endpoint unfortunately only returns metrics for
the specific client queried. In clustered setups where a task
group is running on multiple hosts, this meant data points were
being missed.
The change moves to using the Jobs().Allocations() and
Allocations().Stats() endpoints. These are much more inefficient
than the metrics endpoint, but ensure all task group data points
can be captured no matter their location on a cluster.
closes #124

plugin: fix Nomad APM bug when querying groups on multiple clients.

---

CHANGELOG.md
plugins/builtin/target/nomad/plugin/state.go
policy/handler.go
policy/manager.go
policy/nomad/source.go

This PR fixes an issue where the Autoscaler would fail to re-connect to the Nomad server if the connection was dropped.
The main cause for this issue is that the `policyIDsErrCh` was not being consumed, and so the goroutine monitoring the list of policy IDs would block in case of an error.
I also uncovered some more subtle ways that the Autoscaler could fail to re-connect properly:
* policy handlers would exit in case of connection error and never be re-created.
* the policy list ID monitor would silently `continue` if the Autoscler re-connected to a Nomad cluster where the list of policies were different but the modify index had the same value.
To fix these problems I made a few assumptions:
* Policy handlers only exit when their context is closed. They will keep looping even if an error …

Re-connect to Nomad if connection is lost

---

CHANGELOG.md
docs/plugins/README.md
plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go

This PR introduces the `precision` key for a `RunRequest.Config` for the `target-value` plugin.  `precision` limits how big of a change in the input metric should be considered significant to trigger a scaling event. It also includes small refactorings to improve the `target-value` plugin code.
I set the default precision as `0.01` as a guesstimate. It means the metric needs to change more that 1% of the target value in order for a scale up action to happen. Scaling down is a little higher because we use `math.Ceil` when calculating the next count, so `precision` doesn't affect it as much.
Closes #132

Limit factor precision in target-value plugin

---

demo/vagrant/jobs/grafana.nomad
demo/vagrant/jobs/webapp.nomad

This PR adds a short `cooldown` value to that webapp scaling policy to avoid having to wait the default 5 minutes for the count to return to 1 once `hey` stops.
It also loads the built-in Grafana dashboard from a Docker volume rather than having to download it from the Internet. This removes the need to point to a different GitHub URL when making changes to the dashboard.

Small demo improvements

---

policy/handler.go

Even on local setups, the network traversal when calling for task
group scaling meant the policy handler would exit cooldown and
re-enter for roughly 50ms based on the external last event check.
This seems over zealous so the handler now checks any remaining
cooldown against a default threshold of 1 second. If the remaining
cooldown is less than a second, the handler will not enter cooldown
and continue with normal operations.
The second value was chosen as any less seems to be worthless;
anything higher could impact certain configurations more than
desired.
closes #138

agent: only enter out-of-bounds cooldown if time greater than 1s.

---

demo/vagrant/files/dashboard.json
demo/vagrant/jobs/autoscaler.nomad

I refactored the promtail config a bit to turn most of the key value pairs into loki labels, which can be used easily in (future) queries.

turning exposed meta information into labels

---

plugins/strategy/action.go
plugins/strategy/action_test.go

The current implementation of `pushReason` updates the action before pushing the action's reason into the stack. This causes the previous reason to be lost.
In the screenshot above, the event at the top has the right stack, while the event at the bottom has the current, wrong stack logic.

Fix reason stack to avoid overwriting previous reason

---

plugins/manager/external.go
plugins/manager/manager.go
plugins/plugin.go

`cfg.Name` is the name of the block, but we need the name of the binary when starting the plugin, which is stored in the `driver` field:
```hcl
apm "name" {
driver = "actual-binary-name"
}
```

Fix error when loading external plugins

---

helper/scaleutils/filter.go
helper/scaleutils/filter_test.go
helper/scaleutils/nomad.go
helper/scaleutils/request.go
helper/scaleutils/request_test.go

When performing a scale in action on a pool of Nomad nodes, there
are a number of tasks which should be conducted before the
instances are terminated within the remote infrastructure provider.
The scaleutils helper package provides a method for performing
Nomad node identification, node draining, node drain monitoring
and nodeID translation. This is exposed as a single function so
that target plugin authors can consume the functionality in a
simple manner.
closes #153

helper: add scaleutils to provide cluster scale in helper tasks.

---

agent/config/config.go
agent/config/config_test.go
command/agent.go

The name of the param was chosen to be vague and non-cluster specific so that we can in the future open up the possibility of configuring job scaling policies in the same manner. That being said if we want to change it, I have no feelings on the matter at all.
The config param is optional and defaults to an empty string to allow skipping setting up this policy source if not explicitly desired.
closes #156

agent: add policy dir config param to allow policies from disk.

---

go.mod
go.sum
helper/scaleutils/request.go
plugins/builtin/target/aws-asg/main.go
plugins/builtin/target/aws-asg/plugin/aws.go
plugins/builtin/target/aws-asg/plugin/aws_test.go
plugins/builtin/target/aws-asg/plugin/event.go
plugins/builtin/target/aws-asg/plugin/event_test.go
plugins/builtin/target/aws-asg/plugin/plugin.go
plugins/builtin/target/aws-asg/plugin/plugin_test.go
plugins/builtin/target/aws-asg/plugin/retry.go
plugins/builtin/target/aws-asg/plugin/retry_test.go

This commit adds to initial work for the new AWS AutoScaling Group
target plugin which allows for the scaling of AWS ASGs.
The plugin attempts to perform some basic validation that actions
taken against the AWS API are completed as desired. There is at
this point no reconciliation of failed steps, which should be
added at a later date.
The plugin is within the main repository as we do not currently
have a story of building and releasing plugins from separate repos
which should be looked at in the future. The plugin is also not
launched within the plugin manager, this will be added later when
all the cluster scaling work is tied together.
closes #154

plugins/target/aws-asg: Add new target plugin for AWS ASGs.

---

agent/agent.go
plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go
plugins/strategy/action.go
plugins/strategy/action_test.go
plugins/strategy/strategy.go

The array response from a strategy run was legacy left over from
initial designs and has become redundant. This commit therefore
removes the use of an array in favour of a single action response.
The single response makes the agent evaluation code simpler and
will also make future multi-check work easier to implement.
It was discovered that the length of the response was used to
perform some evaluation logic. The strategy response object has
therefore been updated to include a direction. This is not a new
concept to the Autoscaler and was used in the target-value
strategy plugin originally. It is also used within infra provider
target plugins as they have to deal with calling APIs with
incremental count changes rather than absolute. I believe this is
therefore an acceptable change to the …

strategy: use single action for Run response rather than array.

---

helper/scaleutils/filter.go
helper/scaleutils/nomad.go

In order to filter nodes the caller had to implement logic that
ensured the correct function was called. This puts burden on
callers and results in duplicate code. Providing a function
call off the PoolIdentifier struct means callers can just use this
and the complex logic is hidden.

scaleutils: make node filtering easier with PoolIdentifier func.

---

CHANGELOG.md
policy/nomad/source.go

policy/nomad: fix fast loop when Nomad policy syntax is incorrect.

---

helper/blocking/blocking.go
helper/blocking/blocking_test.go

Per https://www.consul.io/api-docs/features/blocking#implementation-details the index can go backward, or even reset, and thus checking for equality will be more resilient for detecting changes
This will be even more relevant with Nomad supporting snapshot restore

Make IndexHasChanged more resilient to Raft quirks

---

plugins/builtin/target/aws-asg/plugin/plugin.go
plugins/builtin/target/aws-asg/plugin/plugin_test.go

If the target is queried for status while a scaling activity is
in-progress the EndTime will not be populated. The parsing should
therefore protect against this, otherwise the plugin will panic
which is less than ideal, especially during a demo.

plugin/target/aws-asg: fix panic when parsing last ASG activity.

---

agent/agent.go
command/agent.go
main.go
policy/file/source.go
policy/handler.go
policy/manager.go
policy/nomad/source.go
policy/source.go

The file source in particular benefits greatly from being able
to perform reloads. This allows the source to re-read and decode
files which may have changed as well as process new or delete
scaling policies. In order to keep the behaviour as consistent as
possible across all sources the interface has been modified with
this new functionality. The Nomad source noops a reload, but in
the future we may want to use this to reload Nomad client config
params, in particular ACL tokens.
closes #166

agent: allow capturing of SIGHUP to reload policy sources.

---

plugins/builtin/apm/nomad/plugin/job.go
plugins/builtin/apm/nomad/plugin/job_test.go
plugins/builtin/apm/nomad/plugin/metrics.go
plugins/builtin/apm/nomad/plugin/metrics_test.go
plugins/builtin/apm/nomad/plugin/node.go
plugins/builtin/apm/nomad/plugin/node_test.go
plugins/target/target.go
policy/file/source.go
policy/nomad/source.go
policy/nomad/source_test.go
policy/policy.go
policy/policy_test.go

Operators may wish to use the Nomad APM in order to obtain cluster
resource metrics. In order to enhance the Nomad APM changes have
been made to the query formatting allowing for distinction between
taskgroup and node queries. Each has a very seperate path.
The initial implementation does not use blocking queries meaning
performance is suboptimal. A follow up issue will be used to track
this future work.
closes #155

plugin/apm/nomad: support obtaining cluster usage metrics.

---

agent/agent.go
agent/config/config.go
agent/config/config_test.go
command/agent.go

The addition of a policy config block allows us to move and
evaluation interval parameter to this section. The param is only
used for policies and so makes sense in this section. A result of
this move fixes an incorrect detailing of the CLI flag which
referenced its old name.

agent: move and fix default eval interval param to policy block.

---

agent/plugins.go
agent/plugins_test.go
helper/nomad/config.go
helper/nomad/config_test.go
plugins/builtin/apm/nomad/plugin/plugin.go
plugins/builtin/target/aws-asg/plugin/plugin.go
plugins/builtin/target/nomad/plugin/plugin.go
plugins/plugin.go

Plugins such as the AWS ASG target plugin setup a Nomad client in
order to provide scaleutil help. If the operator is using a Nomad
cluster which requires non-default config options, it would be
preferable that they do not have to supply them twice, once to the
agent and again to the plugin.
This changes makes it so that plugin inherit the agents Nomad
configuration by default, reducing the overhead on operators. When
merging config options within the plugin config will take
preference. This allows the operator to provide a subset of params
which are considered specific to the plugin such as ACL token, but
inherit the generic options such as address.
The generic plugin config key "nomad_config_inherit" allows
operators to override default behaviour via a boolean value.
closes #189

plugins: allow all plugins to inherit agents Nomad config.

---

plugins/builtin/target/aws-asg/plugin/aws.go
plugins/builtin/target/aws-asg/plugin/aws_test.go
plugins/builtin/target/aws-asg/plugin/plugin.go
plugins/target/target.go
policy/file/parse_test.go
policy/file/test-fixtures/full-cluster-policy.hcl
policy/policy_test.go

Namespacing the general cluster target params such as node_class
allows easier adoption of future pool identifier such as node
attributes. It also means these will be easier to understand when
namespaced such as "node_attr_random" rather than "attr_random".
Namespacing the AWS specific config params brings consistency to
the plugin. It also means any future plugins that use similar
terminology will have clear differentiators.

policy: namespace cluster target config params.

---

helper/scaleutils/nomad.go

Until the Nomad Autoscaler has the ability to reconcile actions
which have not reached a terminal state, the scaleutils should
protect the node the Nomad Autoscaler is running on from scalein
actions. This gives better assurance that the autoscaler wont
drain the node its on and then not be able to complete the scaling
action.
Even once the autoscaler has reconcile ability, there are some
interesting dicussions to be had about what logic to apply in the
situation where the autoscaler is running as a Nomad job and
identifies its own node for scaling in. In this case, we know it
will never be fully able to complete the action.

scaleutils: protect Autoscaler node from scale in.

---

policy/file/parse_test.go
policy/file/source.go
policy/file/test-fixtures/full-task-group-policy.hcl
policy/nomad/source.go
policy/policy.go
policy/policy_test.go

This adds a validate function to the Policy struct which allows
for the validation ensuring key params are not outside of the
expected.
Ideally both policy sources would use the same function, however,
the Nomad policy source performs validation on the Nomad API
policy struct so there is work to do if we wish to make the
change.

policy: validate key params of policy struct.

---

plugins/manager/manager_test.go

When performing tests on the plugin manager, the launched plugins
were not being killed meaning the process were left orphaned on
the host machine.

plugin/manager: ensure plugins are killed  during manager tests.

---

go.mod
go.sum
policy/nomad/parser.go
policy/nomad/validate.go
policy/nomad/validate_test.go

Nomad 0.12 makes a change to the scaling policy API response
object which results in a change to the Nomad policy parser.
The change moves the max param to a pointer and although Nomad
should never return a nil max value, the parser accommodates it
to be safe.

deps: update Nomad dep to 0.12.0-rc1 to accommodate API changes.

---

demo/vagrant/files/nomad.hcl

Nomad 0.12 has a breaking change that requires a flag to enable absolute path Docker volumes, which we use to load the local Grafana dashboard file.

Fix Vagrant demo for Nomad 0.12

---

CHANGELOG.md
agent/agent.go
agent/plugins.go
agent/plugins_test.go
policy/file/source.go
policy/nomad/source.go
policy/nomad/testing.go
policy/policy.go
policy/policy_test.go

When converting a Nomad APM short query to its long form, there
was an assumption that the plugin was named in its default manner
which caused problems where operators used their own naming
convention.
This change fixes that issue by passing the Nomad APM names to
the function which performs the query transformation. In addition
to simply fixing the issue, this change adds a new policy
processor that can be used to perform validation, canonicalization
and default setting work. I opted for this as it reduced the need
to duplicate work in the two sources. In this case I would have
had to add the APM name list to each source which seems silly and
continues to become annoying in the event we have other
functionality to add to policy parsing and such.
closes #216

policy: fix issue when parsing non-default source name Nomad query.

---

demo/remote/README.md
demo/remote/terraform/env/aws/outputs.tf

Removed the Consul output as the demo doesn't make any calls using
the Consul CLI.
closes #227

demo/remote: add Nomad requirement to doc and remove Consul output

---

demo/remote/terraform/modules/aws-hashistack/templates.tf
demo/remote/terraform/modules/aws-hashistack/variables.tf

When running the demo with a modified node_class, the autoscaler
job and grafana dashboard require modification. To allow custom
classes would require templating of the dashboard and autoscaler
Nomad job even though using a hardcoded class param would not
cause any conflicts or issues within environments.
This change therefore removes the node_class terraform variable
in favour of a simpler hardcoded one.
closes #234

demo/remote: remove use of custom node_class param.

---

.circleci/config.yml
.circleci/config/commands/install-go.yml
.circleci/config/commands/install-golangci-lint.yml
.circleci/config/config.yml

The CI activities of the nomad-autoscaler do not need a dedicated
VM. This should reduce any cost and improve CI run times.

build: use Docker based CircleCI executor instead of VM.

---

agent/config/config.go
command/agent.go

removed in: https://github.com/hashicorp/nomad-autoscaler/pull/197

Remove -scan-interval from help msg, not used anymore

---

agent/config/config.go

When merging the PR the checks showed green so I had assumed the
assosiated lint, test and build phase had also been run. It seems
Circle didn't run the CI phase for the PR so the lint failure was
not caught.
The CircleCI project is configured to build forked pull requests
so I am not sure what happened here. CircleCI status does not
show any issues over the weekend either so probably worth keeping
an eye on this in the future.
Related - https://github.com/hashicorp/nomad-autoscaler/pull/251

agent: fix lint failure within agent config defaults.

---

go.mod
go.sum
helper/scaleutils/nomad.go
plugins/builtin/target/aws-asg/plugin/aws.go
plugins/target/target.go

When performing cluster scaling and removing nodes from the pool
of compute, an operator may optionally wish to have the terminated
node removed from the Nomad node list. This can be performed by
using the node purge API call and is now included as part of the
scaleutils scale in post tasks run.
The default behaviour is that the purge is not run. The operator
can change this by adding a config option "node_purge" to the
target config mapping. The RunPostScaleInTasks func handles
checking the target configuration, so that this work does not need
to be repeated across all cluster scaling plugins.
closes #257

scaleutils: add post scale in task to optionally purge nodes.

---

README.md

0.1.1 only required the Nomad dep upgrdae. The remote agent does
not need 0.12.4 running.

docs: revert change in requirement matrix.

---

helper/ptr/ptr.go

This is useful for testing Nomad API JobSpec objects which use
string pointers in many places.

helper/ptr: add string to pointer method.

---

plugins/builtin/target/nomad/plugin/plugin.go
plugins/builtin/target/nomad/plugin/plugin_test.go
plugins/builtin/target/nomad/plugin/state.go
plugins/builtin/target/nomad/plugin/state_test.go

Tested locally via vagrant demo with success.
closes #276

target/nomad: support for namespaced jobs in scale and status RPC.

---

version/version.go
version/version_test.go

Brings the autoscaler inline with HashiCorp products and expected
version formatting.

version: allow setting custom metadata on version output.

---

agent/agent.go
agent/config/config.go
agent/config/config_test.go
command/agent.go

This PR allows for operators to configure the eval broker via the configuration file. It also renames some of the fields to better match their intended use:
```hcl
policy_eval {
ack_timeout = "10m"
delivery_limit = 3
workers = {
cluster    = 0
horizontal = 2
}
}
```
Docs and CLI flags will come in a separate PR.

Add eval broker configuration and validate agent config

---

version/version.go
version/version_test.go

When the CI pipeline builds the final binary, `GitDescribe` is define with all segments already, so the CLI shouldn't add any extra info (apart from the commit hash).

Fix version geneartion logic with GitDescribe

---

.circleci/config.yml
.circleci/config/config.yml

Dockerhub is going to rate limit unauthenticated pulls.
Use our internal mirror for builds running through CircleCI.

Use Dockerhub Mirror.

---

demo/vagrant/dynamic-app-sizing/Vagrantfile
demo/vagrant/dynamic-app-sizing/jobs/das-autoscaler.nomad
demo/vagrant/dynamic-app-sizing/jobs/das-load-test.nomad
demo/vagrant/dynamic-app-sizing/jobs/example.nomad

The nginx task was mounting the config file also as a file inside the Docker container. When Consul Template re-rendered the file, the inode reference would change, so nginx wouldn't see the updated version, even after a `SIGHUP`

demo/das: update limits and fix nginx config file reload

---

agent/agent.go
agent/http/agent.go
agent/http/agent_test.go
agent/http/health_test.go
agent/http/metrics.go
agent/http/metrics_test.go
agent/http/server.go
agent/http/testing.go
agent/http_handler.go
agent/testing.go
command/agent.go

This PR adds a new HTTP endpoint (`/v1/agent/reload`) that can be used to trigger the agent to reload, similarly to a `SIGHUP` signal, which can be useful in situations where file policies are rendered by a sidecar, which can then notify the Autoscaler to reload when policies are modified.

add HTTP endpoint to reload agent

---

demo/remote/aws_autoscaler.nomad
demo/remote/azure/terraform/modules/azure-hashistack/templates/azure_autoscaler.nomad
policy/file/parse.go
policy/file/parse_test.go
policy/file/source.go
policy/file/source_test.go
policy/file/test-fixtures/full-cluster-policy.hcl
policy/file/test-fixtures/full-task-group-policy.hcl
sdk/policy.go
sdk/policy_test.go

This PR allows for policy files to store multiple policies. This is a useful feature when using the Autoscaler as a Nomad job as it allows for dynamic policy generation based on Consul keys and other sources supported by Nomad's `template` stanza`.
It changes the format of policy file slightly by wrapping it around a `scaling` block, similarly to how a horizontal policy is defined in the jobspec.
Each `scaling` stanza requires a label so that policies within the same file can be differentiated.
This jobspec:
```hcl
job "autoscaler" {
datacenters = ["dc1"]
group "autoscaler" {
count = 1
task "autoscaler" {
driver = "docker"
config {
image   = "hashicorp/nomad-autoscaler:0.1.0"
command = "nomad-autoscaler"
...
}
template {
data = <<EOF
{{ $prefix := "nomad-autoscaler/policies" }}
{{ range …
```

Allow multiple policies per file

---

demo/vagrant/dynamic-app-sizing/jobs/das-autoscaler.nomad
demo/vagrant/dynamic-app-sizing/jobs/prometheus.nomad

Updates the job files used within the Vagrant DAS demo to use the
group level network stanza.
This change also adds a Consul health check for the Autoscaler
using the health endpoint. This matches what is done within the
horizontal vagrant demo.
closes #327

demo/vagrant/das: remove use for deprecated network spec params.

---

plugins/builtin/apm/nomad/plugin/job.go
plugins/builtin/apm/nomad/plugin/job_test.go
plugins/builtin/apm/nomad/plugin/metrics.go
plugins/builtin/apm/nomad/plugin/metrics_test.go

Following the work on #324, this PR adds a new query type for the Nomad APM to use percentage values based on allocated totals rather than looking at the entire cluster.

Query Nomad APM for memory values relative to task group

---

command/agent.go

Figured it'd be nice to know which version produced which logfiles while debugging issues.  Change emits: 
```
➜ ./nomad-autoscaler agent
2021-01-12T12:35:59.415-0500 [INFO]  agent: nomad-autoscaler version v0.3.0-dev starting````

Print autoscaler version to log on agent startup

---

agent/config/config.go
agent/config/config_test.go
agent/http/server.go
agent/http/testing.go
command/agent.go

The Nomad Autoscaler is mildly complex and debugging problems can be tricky when they are related to items such as go routine deadlocks. The optional pprof endpoints allow developers and operators to easily obtain profiling data from the Nomad Autoscaler, no matter the persons ability with the Go programming language.
We have no control over the API, therefore they do not sit under the `/v1` prefix.
p.s. @cgbaker sorry for adding more endpoints!

agent: add pprof HTTP debug endpoints.

---

policyeval/base_worker.go

The Nomad Autoscaler v0.0.x had a single goroutine evaluating policies. When we introduced multiple `check`s in the v0.1.0 release we tried to parallelize as much work as possible to keep the goroutine as fast as possible.
This created a race condition where the worker and the checks could be stuck waiting on each other.
In the v0.2.0 release we introduced the EvalBroker and Workers, so parallelization can now be provided at a higher level (per policy). 
This PR turns the policy evaluation process into a linear execution to prevent the Worker from getting stuck. It also introduces checks for `ctx.Done()` before potentially long-running operations happen (namely, around plugin calls).
Future work will include a heartbeat mechanism to detect and recreate workers that get stuck, then we can …

Don't block worker while evaluating a policy

---

agent/config/config.go
agent/config/config_test.go

The Autoscaler was accidentally overriding the defaults returned by Nomad's [`api.DefaultConfig()`](https://github.com/hashicorp/nomad/blob/v1.0.2/api/api.go#L243). 
I couldn't see a reason why the Autoscaler would need to set default values on its own, so I just removed them. But I could be missing something.
It's also not a breaking change since the default values being set are the same as `api.DefaultConfig()` defines.
Closes #357

Use default values for the Nomad client as provided by the `api` package

---

plugins/builtin/target/gce-mig/plugin/gce.go
plugins/builtin/target/gce-mig/plugin/gce_test.go

Implement new cluster scaling config `node_drain_ignore_system_jobs` to the `gce-mig` target.
Closes #366.

Add `node_drain_ignore_system_jobs` to `gce-mig` target

---

agent/agent.go
agent/agent_test.go
agent/plugins.go
agent/plugins_test.go
sdk/helper/nomad/config.go
sdk/helper/nomad/config_test.go

Fix an issue where parameters from the Nomad default config, which includes env var discovery, were not being correctly passed onto plugins which use a Nomad client.
The agent is now responsible for merging its own Nomad config with the Nomad API default configuration and storing this for use for all downstream clients where desired.
Viewed from a plugin receiving client config options, the following chain occurs starting from lowest to highest precedence:
- Nomad API defined default parameters
- Nomad API defined environment variables
- Nomad Autoscaler config file parameters, nomad block
- Nomad Autoscaler CLI parameters
- Nomad Autoscaler config file parameters, plugin specific block
closes #380

agent: fix Nomad config merging to pass env vars to plugins.

---

plugins/builtin/apm/prometheus/plugin/plugin.go

This little manoeuvre's gonna save us 4 nanoseconds.

plugin/apm/prometheus: only access config map once to set config.

---

plugins/builtin/apm/nomad/plugin/node.go
plugins/builtin/target/aws-asg/plugin/plugin.go
plugins/builtin/target/azure-vmss/plugin/plugin.go
plugins/builtin/target/gce-mig/plugin/plugin.go
sdk/helper/scaleutils/filter.go
sdk/helper/scaleutils/filter_test.go
sdk/helper/scaleutils/status.go

In situations where cluster scaling evaluations are triggered at
a rate faster than cluster scaling actions can complete,
the autoscaler would drain more and more nodes, eventually leaving
the pool without any.
The fix adds better, more thorough node pool filtering to error in
situations where the nodes within a pool are considered unstable.
This ensures the Nomad Autoscaler will only perform cluster scaling
evaluations when we can be sure the state is stable and known.
closes #376

scaleutils: filter nodes to ensure unstable pools do not run eval.

---

sdk/helper/scaleutils/nomad.go

The IgnoreSystemJobs DrainSpec param was not being passed to the
drain monitor as this was previously hard-coded and not exposed
to users.
Recent updates had exposed this as a config param to users via
scaling policies and is sent correctly when calling the Nomad API
and draining a node. However, the drain monitor was still using
a hardcoded false value, meaning it would wait endlessly for all
allocs to be drained, including system allocs which were never
going to be drained.
closes #387

scaleutils: pass ignoreSystem drainspec param to drain monitor.

---

plugins/builtin/target/aws-asg/plugin/aws.go

It could also be worth adding logic to `RunPostScaleInTasks` to check the node state before purging on some retry interval to ensure the purge call has the desired affects. I'll raise a followup issue to track this.
closes #391

plugin/target/aws-asg: check instances in non-running state.

---

agent/agent.go
agent/config/config.go
command/agent.go
plugins/builtin/target/nomad/plugin/plugin.go
plugins/manager/manager.go
policy/manager.go
policy/nomad/source.go

This PR expands the effect of sending a `SIGHUP` signal to reload the Autoscaler configuration.
It specifically reloads plugin configurations, stops/starts plugins if their blocks are removed/added, and updates instances of Nomad clients (withing plugins and the policy source).
Other configuration values are also updated in memory, but have no effect (for example, increasing the number of workers for a queue).
Closes  #375

Expand SIGHUP handling

---

policy/manager.go

policy-manager: metric emit loop should use child context.

---

CHANGELOG.md
agent/http/agent_test.go
agent/http/health_test.go
agent/http/metrics.go
agent/http/metrics_test.go
agent/http/server.go
agent/http/testing.go
command/agent.go

If the user has disabled Prometheus metrics and a request is
sent to the metrics endpoint requesting Prometheus formatted
metrics, then the request should fail.
The returned response code copies that of Consul and Nomad,
to provide a consistent user experience.
closes #398

agent: return req error if prometheus metrics are disabled.

---

agent/config/config.go
agent/config/config_test.go

Calling `Merge` or any of the block-specific `merge` methods would `panic` because we were dereferencing the pointer before checking for `nil`.
Fixes #419

Check for nil before dereferencing agent config pointer

---

command/agent.go
sdk/helper/flag/flag.go
sdk/helper/flag/flag_test.go

The `EvaluateAfter` config will be moved to a new configuration block, so it was left out of this PR.
Closes #291

add CLI flags for PolicyEval config

---

policy/handler.go

In some situations (such as agent shutdown) the policy monitor might return a `nil` error, causing a panic.

Check for nil result to prevent panic

---

plugins/builtin/target/aws-asg/plugin/aws.go
plugins/builtin/target/aws-asg/plugin/aws_test.go
plugins/builtin/target/aws-asg/plugin/event.go
plugins/builtin/target/aws-asg/plugin/plugin.go
plugins/builtin/target/aws-asg/plugin/status.go
plugins/builtin/target/aws-asg/plugin/status_test.go
sdk/helper/scaleutils/cluster.go
sdk/helper/scaleutils/node_drain.go

closes #361 
closes #412 
This changes the AWS ASG plugin to use `TerminateInstanceInAutoScalingGroup` when scaling in nodes rather than a call against the ASG to detach instances and then another to terminate instances. This solves a core bug, whereby decrementing an ASG accepts a maximum of 20 instance IDs.
The downside of moving to this function, is that unlike Azure and GCP, AWS ASG only accepts a single instance ID per call to terminate an instance from an ASG. In order to accommodate this, the plugin includes some additional logic in order to understand and correctly respond to situations where, in a single scaling event, some termination calls might succeed, and others might fail. This creates a partial success. In partial success situations, the plugin attempts to toggle the …

plugin/target/aws-asg: use single ASG call rather than split ASG/EC2 on scale-in.

---

GNUmakefile

I will raise a followup issue to improve this process; ideally in a way that just iterates the directory rather than requiring manual updates to the makefile.

makefile: add targets for fixed-value and pass-through plugins.

---

policyeval/base_worker.go

This ensures consistency across the codebase and removes the use of what is a Golang specific style making log aggregation and parsing easier.

policyeval: log error messages with error key.

---

plugins/builtin/strategy/pass-through/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go

With [`query` being optional](#442), there's a possibility that strategy plugins are called with empty metric results. So return a no-op scaling action.

Return no-op scaling action when there are no metrics

---

policy/nomad/test-fixtures/src/strategy-without-metric.hcl
policy/nomad/test-fixtures/strategy-without-metric.json.golden
policy/nomad/validate.go
policy/nomad/validate_horizontal.go
policy/nomad/validate_test.go
policyeval/base_worker.go
sdk/policy.go

Some strategy plugins don't require an APM query result (for example, `fixed-value`), so the PRs modifies the scaling policy validation rules to allow checks without a `query`.

Make `query` optional inside checks

---

policy/file/source.go

When running the Autoscaler at `INFO` level (the default), there's no indication that a policy file has been properly loaded, which is a useful information to have early-on.

Upgrade policy file monitoring log to info

---

agent/config/config.go
plugins/builtin/apm/prometheus/plugin/plugin.go
plugins/builtin/strategy/fixed-value/plugin/plugin_test.go
plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go
plugins/builtin/target/gce-mig/plugin/gce.go
plugins/builtin/target/nomad/plugin/state_test.go
policy/handler.go
policy/nomad/source.go
policy/nomad/validate.go
policy/nomad/validate_horizontal.go
policy/nomad/validate_test.go
policy/policy.go
policyeval/broker.go

Using the stdlib `errors.New` call to create errors that are not formatted is quicker and more memory efficient. This change therefore moves all non-formatted error creations to use this func.
Just imagine what we can achieve with the 80ns we save each time.

chore: don't use fmt.Errorf when not formatting the error.

---

policy/ha/filter.go
policy/ha/source.go
policy/ha/source_test.go
policy/ha/testing_test.go
policy/source.go

this provides a new `policy.Source`, which accepts a policy filter and an upstream `policy.Source` and applies the filter to the results of `MonitorIDs` on the upstream.

new policy.Source for filtering policies for HA capability

---

policy/policy.go
policy/policy_test.go
sdk/helper/scaleutils/cluster.go
sdk/helper/scaleutils/cluster_test.go
sdk/helper/scaleutils/node_identifier_test.go
sdk/helper/scaleutils/nodepool/class.go
sdk/helper/scaleutils/nodepool/datacenter.go
sdk/helper/scaleutils/nodepool/datacenter_test.go
sdk/helper/scaleutils/nodepool/nodepool.go
sdk/helper/scaleutils/nodepool/nodepool_test.go
sdk/policy.go
sdk/policy_test.go
sdk/target.go

closes #459 
When understanding the nodes which form a scalable pool of resource, the Nomad Autoscaler uses the nodepool interface which provides functionality to understand node grouping. This change adds a new implementation, `datacenter`, which allows nodes to be group according to their datacenter configuration option.
The cluster policy validation has been updated to account for this change. Particuary the `node_class` and `datacenter` options are mutually exclusive. The new validation functions use the `helper/error` pkg to create better formatted errors. Work to update the entire error chain will be conducted in a follow up PR. 
The Nomad project site will need updating to document the new config option. It may also prove valuable to add a demo, or at least commented out examples …

scaleutils: add datacenter nodepool implementation

---

plugins/builtin/target/aws-asg/plugin/aws.go
plugins/builtin/target/aws-asg/plugin/aws_test.go

A user specific region configuration option should take precedence
over other options. This change therefore updates the flow in
which the AWS config is populated. In situation where AWS and the
operator do not provide an option, the default is applied.
The change itself is hard to automatically test at the moment as
the behaviour changes depending whether you have the EC2 metadata
service available. The test added is aimed at situations where the
plugin is not running with the EC2 metadata service available.
#473 has been raised to track better testing where the EC2 metadata
service is available.
closes #472

plugins/target/aws-asg: correctly order region config setting.

---

plugins/builtin/strategy/pass-through/plugin/plugin.go
plugins/builtin/strategy/pass-through/plugin/plugin_test.go
plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go
policyeval/base_worker.go

There is a small difference between a strategy determining that the count value shouldn't change as opposed to the strategy not being able to compute it.
In the first case, the new count is successfully calculated but it happens to be equal the current count. In the second case, the strategy is unable to determine what to do.
This difference is important because a `none` scaling direction takes precedence over a `down` action. Return `none` instead of `nil` can cause a `down` check to be ignored.

Fix to return `nil` instead of `none` action from strategies

---

policy/handler.go
policy/manager.go

This helps keeps consistency across error logging where error
messages can be groked or filtered using context.

policy: log error messages using contextual params.

---

sdk/helper/metrics/metrics.go
sdk/helper/metrics/metrics_test.go

When running in HA and therefore when each agent has a unique ID,
it will be useful to have this ID as a default label. This allows
easier understanding across telemetry, logs and service discovery
processes.
The new package wraps the metrics library calls, ensuring default
and additional labels are always added where required.
The new code isn't currently utilised, this work will be performed in
a follow up PR targeting the feature branch.

helper: add metric pkg to allow setting default labels.

---

sdk/helper/scaleutils/nodeselector/least_busy.go

This adds additional API calls when performing the least busy node
selector as a best effort to work on cluster that running Nomad
versions before v1.0.0.
v1.0.0 including API functionality which allows node resources to
be include in the stub list node object which is used when
performing least busy calculations. In version prior to this, the
information is only available within the node info object.
closes #506

scaleutils: fix least busy selector on clusters older than v1.0.0

---

CHANGELOG.md
policy/handler.go
policy/mutators.go
policy/mutators_test.go

The Nomad APM uses the Nomad API to retrieve information about allocations and nodes. Usually, the choice of metric source should not impact the choice of target defined in a policy, but when using the Nomad APM to perform cluster scaling to `0` presents there is a problem to scale back up since, once the cluster reaches zero clients, there's nothing to query for metrics. 
There is also no meaningful default value to return in this case. The metrics supported by the Nomad APM for cluster scaling are percentage of CPU and memory allocated. For zero clients these values are 0% and 100% at the same time, and different policy strategies would require interpreting in one or another. Or not mater at all!
For example, using the `target-value` strategy with `target = 70` (i.e., 70% CPU usage as …

Add policy mutators to prevent cluster scaling to zero with the Nomad APM

---

CHANGELOG.md
policy/policy.go
policy/policy_test.go
sdk/helper/scaleutils/nodepool/combined.go
sdk/helper/scaleutils/nodepool/combined_test.go
sdk/helper/scaleutils/nodepool/nodepool.go
sdk/helper/scaleutils/nodepool/nodepool_test.go

The initial implementation for the node filtering would only take either node class or datacenter as the filter input. But as explained in #531, there are valid use cases where defining both is required in order to properly match Nomad clients with cloud instances.
This PR creates a new `ClusterNodePoolIdentifier` called `combinedClusterPoolIdentifier` that can be used to merge other identifiers, applying a simple `and` or `or` logic. 
When both `node_class` and `datacenter` are present in a scaling policy, the Autoscaler will use this combined identifier to merge the existing `NewNodeDatacenterPoolIdentifier` and `NewNodeDatacenterPoolIdentifier` logic with the `and` operator. 
In the future we may add an option to use the `or` operator, but it's not clear to me if there is any real …

Allow datacenter and node class filtering

---

CHANGELOG.md
agent/config/config.go
agent/config/config_test.go

When these new strategy plugins were added, we forgot to update the agent to auto-dispense them. 
I wonder if we should just auto-dispense _all_ builtin plugins and add a new flag to allow disabling specific ones if needed, but some of them require additional configuration (like `aws-asg`, `prometheus` etc), so the user would have to declare them anyway.
It would be cool if we could detect plugins that don't require additional config and auto-dispense them, but I couldn't think of a way to easily check this.
Closes #532

Dispense fixed-value, pass-through, and threshold strategy plugins by default

---

CHANGELOG.md
plugins/builtin/strategy/threshold/plugin/plugin.go
plugins/builtin/strategy/threshold/plugin/plugin_test.go

When there aren't enough metric values within the bound values, the Autoscaler should emit a `none` scaling action since the query values are not enough to cause a change.
Closes #529

Fix threhold plugin logic when there are not enough metrics within bounds

---

CHANGELOG.md
plugins/builtin/target/nomad/plugin/plugin.go

Read the right config key when logging the error message.

Fix error message when job scale request fails

---

plugins/builtin/target/nomad/plugin/plugin.go
plugins/builtin/target/nomad/plugin/plugin_test.go
plugins/builtin/target/nomad/plugin/state.go
plugins/builtin/target/nomad/plugin/state_test.go
policy/handler.go

The Nomad target plugin caches job and group status locally to avoid querying the Nomad API every time a policy is evaluated. This is done by having background gorotuines that use blocking queries to update the local state whenever the job scale status changes.
The current implementation has a bug that can be triggered when the Nomad API returns an error at the first run. The blocking query look gets stuck in [this loop](https://github.com/hashicorp/nomad-autoscaler/blob/v0.3.3/plugins/builtin/target/nomad/plugin/state.go#L135-L157) causing [`jsh.handleFirstRun()`](https://github.com/hashicorp/nomad-autoscaler/blob/v0.3.3/plugins/builtin/target/nomad/plugin/state.go#L172) to never be called. This, in turn, blocks the entire plugin since the plugin `Status` call would be waiting …

Prevent the Nomad target plugin from being blocked

---

CHANGELOG.md
plugins/builtin/target/nomad/plugin/plugin.go
policyeval/base_worker.go
sdk/target.go

The Autoscaler is fairly likely to encounter active deployments during policy evaluations, either due to previous scaling actions that are taking longer than the policy `evaluation_internval` and `cooldown`, or due to manual job updates by operators.
This situation is usually not detrimental to the overall scaling progress since the deployment is expected to eventually complete and future policy evaluations will correct the group `count` if necessary.
This PR reduces the log level for when this happen from an `ERROR` to just `INFO`. 
It also introduces a new concept of `TargetScalingNoOpError` which is a special error type that target plugins can use in situations like this, where the scaling action request didn't actually complete, but that's not really a problem.
Closes #515

Downgrade error message from app scaling due to active deployment

---

CHANGELOG.md
plugins/builtin/apm/prometheus/plugin/plugin.go
plugins/builtin/apm/prometheus/plugin/prometheus.go
plugins/builtin/apm/prometheus/plugin/prometheus_test.go

This PR is a WIP to add the ability to set additional headers in the
prometheus APM client.  Right now I have the roundtripper adding a
suitable header for cortex, but obviously it cannot be hard coded.
The config type for this plugin is flat, and I'm trying to determine
the best way to include multiple header values in this type.  Guidance
is appreciated to make sure this fits in with the rest of the code
style in the repo.
Resolves #522

Allow setting additional headers in prometheus APM client

---

CHANGELOG.md
plugins/builtin/target/aws-asg/plugin/aws.go
plugins/builtin/target/aws-asg/plugin/aws_test.go
plugins/builtin/target/azure-vmss/plugin/azure.go
plugins/builtin/target/azure-vmss/plugin/plugin.go
plugins/builtin/target/gce-mig/plugin/gce.go
plugins/builtin/target/gce-mig/plugin/mig.go
sdk/helper/scaleutils/cluster.go
sdk/helper/scaleutils/node_identifier.go
sdk/helper/scaleutils/node_identifier_test.go

This PR makes a few changes in the way nodes are selected for cluster scale in action.
When scaling in a cluster, we must find a set of clients that meet two criteria:
- They match the filtering criteria specified in the policy (`node_class` and/or `datacenter`).
- They belong to the remote service being targeted.
Selecting which nodes to remove can only be reliably executed once both filters are applied since clients in different remote services can have matching filtering criteria (for example, clients with the same `node_class` but in different AWS ASGs).
Currently, the list of nodes that match the filtering criteria is being reduced prematurely to the number of next count, which increases the odds of nodes that don't belong to the remote service being picked. These nodes will cause …

Perform remote service filtering before selecting nodes when scaling in cluster

---

CHANGELOG.md
agent/agent.go
agent/config/config.go
agent/config/config_test.go
command/agent.go
command/agent_test.go
command/test-fixtures/agent_config_full.hcl
policy/manager.go

This PR builds on top of the approach taken in #525 but allows a more flexible way to define which policy sources should be enabled.
It introduces a new configuration block called `source` that can be placed within the existing `policy` block. Currently this block takes only a label that specifies which source it controls and a boolean attribute to enable or disable it:
```hcl
policy {
source "nomad" {
enabled = false
}
}
```
Both `file` and `nomad` sources are initially enabled by default, with `file` requiring that `policy -> dir` is also defined to be fully enabled, so everything remains backwards compatible.
The CLI flag parsing is a bit different than others, and it special cases the existing policy sources. This seems fine to me, as all policy sources are internal and having CLI …

Allow enabling and disabling policy sources

---

CHANGELOG.md
plugins/builtin/apm/datadog/plugin/plugin.go
plugins/builtin/apm/datadog/plugin/plugin_test.go

Following the instructions in https://github.com/DataDog/datadog-api-client-go#changing-server, this PR reads a new value called `site` from the plugin config and sets it in the Datadog client context.
Closes #498

Allow setting Datadog site

---

agent/config/config_test.go

I hit this problem in
https://app.circleci.com/pipelines/github/hashicorp/nomad-autoscaler/1277/workflows/811c0700-78f4-4ec2-b82a-712473d7af93/jobs/4366
The policy sources are already being tested in `assert.Equal(t, expectedResult.Policy, actualResult.Policy)` so we don't need specific `ElementsMatch` check anymore.

Sort policy sources to prevent flaky test results

---

CHANGELOG.md
plugins/builtin/apm/prometheus/plugin/plugin.go
plugins/builtin/apm/prometheus/plugin/prometheus.go
plugins/builtin/apm/prometheus/plugin/prometheus_test.go

Manually testes using the instructions in https://prometheus.io/docs/guides/tls-encryption/ but using [these steps](https://gist.github.com/croxton/ebfb5f3ac143cd86542788f972434c96) to generate the certificate, otherwise I would get this error from the Prometheus client:
```
2021-11-24T10:07:53.393-0500 [WARN]  policy_eval.worker: failed to run check: id=377a4f0d-834f-e87c-9cbe-8a05d4e91b57 policy_id=7fe5c606-3d3b-ecd0-ed70-06566acd04bb queue=horizontal target=nomad-target error="failed to query source: failed to query: Post "https://example.com:55001/api/v1/query_range": x509: certificate relies on legacy Common Name field, use SANs instead"
```
Closes #497

Add support for TLS CA certificate on Prometheus APM

---

CHANGELOG.md
policy/handler.go
sdk/policy.go
sdk/policy_test.go

In rare cases, it's possible that the policy handler doesn't receive the initial policy content before the default timeout (3m). When this happens, the Autoscaler will `panic` since it will try to validate a `nil` policy without any safeguards.
This PR moves some of the logic from `generateEvaluation` to `handleTick` so a `nil` check is performed earlier and it also updates the policy `Validate` function to not panic on `nil`.

Fix panic when first policy read timeout

---

CHANGELOG.md
plugins/builtin/apm/datadog/plugin/plugin.go

err is != nil for 429s too so the code will never return the specific 429 error msg

[APM Datadog] return 429 specific error

---

CHANGELOG.md
policy/file/parse_test.go
policy/file/test-fixtures/full-cluster-policy.hcl
policy/nomad/parser.go
policy/nomad/parser_test.go
policy/nomad/source.go
policy/nomad/test-fixtures/full-scaling.json.golden
policy/nomad/test-fixtures/src/full-scaling.hcl
policyeval/base_worker.go
sdk/policy.go
sdk/policy_test.go

Introduce two new configuration options (`on_error` and `on_check_error`) to allow operators fine-grain control on how to handle errors when checks are being evaluated.
`on_check_error` is set at policy level and is applied to all `check` by default. Each `check` may override this setting using `on_error`.
For example, this policy will fail its evaluation if _any_ `check` fails:
```hcl
scaling "batch" {
enabled = true
min     = 0
max     = 5
policy {
cooldown            = "1m"
evaluation_interval = "10s"
on_check_error      = "fail"
check "batch_jobs_in_progess" {
source = "datadog"
query  = "avg:proxy.backend.response.time{proxy-service:web-app}"
strategy "noop-strategy" {}
}
check "noop" {
source = "noop-apm"
query  = "fixed:5"
strategy "noop-strategy" {}
}
target "noop-target" {}
}
} …
```

Add `on_error` and `on_check_error` config

---

CHANGELOG.md
policy/file/parse_test.go
policy/file/test-fixtures/full-cluster-policy.hcl
policy/nomad/parser.go
policy/nomad/parser_test.go
policy/nomad/source.go
policy/nomad/test-fixtures/full-scaling.json.golden
policy/nomad/test-fixtures/src/full-scaling.hcl
policyeval/base_worker.go
sdk/policy.go

Grouped checks are checks that have the same value for the new `group`
configuration. Checks that are part of the same group have their results
compared to one another resulting in a single action representing all
checks. This final result is then compared to the rest of the checks.
Grouped checks should be used when multiple checks use the same or
correlated data as input. In these situations it's expected that only
one check (or a handful of them) will actually have enough data to make
a decistion.
For example, consider these two checks that monitore the percentage of
memory usage in a cluster:
```hcl
check "memory-low" {
source = "prometheus"
query  = "..."
strategy "threshold" {
upper_bound = 30
delta       = -1
}
}
check "memory-high" {
source = "prometheus"
query  = "..."
strategy …
```

Add grouped checks

---

CHANGELOG.md
plugins/builtin/target/aws-asg/plugin/aws.go
plugins/builtin/target/aws-asg/plugin/plugin.go

Make the use the EC2 instance role as the credential source opt-in, reverting the previous behaviour of using the default credencial chain unless specified otherwise.
To force the use of the EC2 instance role set the new config `aws_credential_provider` to `ec2_role`:
```hcl
target "aws-asg" {
driver = "aws-asg"
config = {
aws_credential_provider = "ec2_role"
}
}
```
Closes #573
Closes #575

plugin/target/aws: fix credential chain

---

CHANGELOG.md
plugins/builtin/target/aws-asg/plugin/aws.go
plugins/builtin/target/aws-asg/plugin/plugin.go

The maximum waiting time for checking the status of the ASG is 2 minutes, which is not configurable.
When using the ASG target plugin and downscaling, the ELB connection draining could take more
than 2 minutes. If this happens, Nomad will purge the nodes without waiting for the ASG to remove
the instances.
Logs:
```
2022-07-28T15:48:51.939Z [ERROR] internal_plugin.aws-asg: failed to ensure all activities completed: action=scale_in asg_name=preproduction/nomad error="reached retry limit"
2022-07-28T15:48:52.123Z [INFO]  internal_plugin.aws-asg: successfully purged Nomad node: node_id=34862212-f89a-b107-903d-f4036a44543d nomad_evals=["88a3c562-31e6-f303-cae3-1289bd924958", "b0b08d76-0c2c-e5f3-1b8d-d6f032cd89aa"]
```
So, this commit adds a new config property called `retry_attempts`, which …

feat(aws-asg): add `retry_attempts` configuration to customize the maximum waiting time

---

.github/workflows/nightly-release.yml

The GHA version pinning bot upgraded all action versions, which pulled several breaking changes from `actions/github-script`.
The one that affected us here is that the `git` context was moved to `rest` (https://github.com/actions/github-script/issues/328).
Failed run: https://github.com/hashicorp/nomad-autoscaler/actions/runs/4848130638
Successful run: https://github.com/hashicorp/nomad-autoscaler/actions/runs/4853454638

ci: fix nightly release

---

CHANGELOG.md
agent/agent.go
agent/http/health.go
go.mod
go.sum
sdk/helper/scaleutils/cluster.go
sdk/helper/scaleutils/node_drain.go
sdk/helper/scaleutils/node_drain_test.go

Issue found [here](https://github.com/hashicorp/nomad-autoscaler/issues/627)
The nomad autoscaler should be able to set up specific metadata for nodes that are being drain, in order to pick up where it left off in case of a failure. This PR introduces the change. It also adds an interface to make decoupling from the nomad cluster easier for testing on this feature and maybe some more in the future.

func: add metadata for drained nodes

---

plugins/builtin/apm/nomad/plugin/job.go

plugin/apm/nomad: fix spelling mistake in log lines.

---

.github/dependabot.yml

Once merged, I will update enterprise to only check on modules which are specific to that repo.

deps: add Dependabot config file to control run

---

go.mod
go.sum

go.mod had an incorrect hash for the Nomad API package, probably due to a feature branch rebase.

build: incorrect nomad/api version in go.mod

---

go.mod
go.sum

Current Nomad main:
```
$ git show b977c377888a
fatal: ambiguous argument 'b977c377888a': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```
```
$ git --no-pager show 3d624388765f
commit 3d624388765f895a020d20a9767f2dced0b108c7 (HEAD -> main, origin/main, origin/HEAD)
Author: Piotr Kazmierczak <470696+pkazmierczak@users.noreply.github.com>
```

deps: update Nomad API to existing commit SHA

---

CHANGELOG.md
plugins/builtin/target/nomad/plugin/plugin.go
plugins/builtin/target/nomad/plugin/state.go

I noticed while working on another issue that `/v1/scaling/policy/{policy-id}` got started again after job purge/re-create, but `/v1/job/{job-id}/scale` did not.  I was surprised not to find an open issue for this, but maybe I missed it.
Instead of trying to un-stop the existing handler, I opted to just start a new one.  Let me know if this is horribly inefficient in some way that I'm not anticipating.

Handle jobs being deleted and re-created

---

CHANGELOG.md
policy/file/source.go
policy/file/source_test.go

Fixes #519 "failed to read policy in time" errors, at least those which occur due to Handlers getting re-started, but then not receiving file policies, because they already exist from the point of view of the file policy Source.
When the policy Manager creates and runs new Handlers, the new Handler needs to receive a policy on its h.ch, or h.handleTick() will have a nil currentPolicy, which results in "timeout: failed to read policy in time"
So, each time Handler asks a Source to MonitorPolicy(), the Source needs to send a policy back to the Handler (via MonitorPolicyReq.ResultCh: h.ch), even if the Source already knows the policy from a previous run.
---
I want to acknowledge that, after I banged my head against it for awhile, I found that @Seros totally had a handle (heh) on it already …

Recover file policies after manager soft-restarts (from Nomad API errors)

---

agent/config/config.go
command/agent_test.go
command/test-fixtures/agent_config_full.hcl

This change ensures the CLI flags and config file options use the same naming. It means switching between either has a lower overhead and ensures a better UX.

agent: standardize high availability config options.

---

CHANGELOG.md
sdk/helper/scaleutils/cluster.go
sdk/helper/scaleutils/nodepool/nodepool.go
sdk/helper/scaleutils/nodepool/nodepool_test.go
sdk/helper/scaleutils/nodepool/pool.go
sdk/helper/scaleutils/nodepool/pool_test.go
sdk/target.go

Add the `node_pool` node selector option to filter nodes by their `node_pool` value.
Closes #749

cluster: support `node_pool` value as filter

---

GNUmakefile

When developing, it's useful to have the `nomad-autoscaler` binary available in `$GOPATH` so it's easier run them.

build: copy binary to `$GOPATH` on `make dev`

---

CHANGELOG.md
plugins/builtin/apm/nomad/plugin/job.go
plugins/builtin/apm/nomad/plugin/job_test.go
policy/nomad/source_test.go
policy/policy.go
policy/policy_test.go
sdk/target.go

The Nomad Autoscaler agent can only target a single namespace, but when using the wildcard (`*`) value it is possible to monitor policies for all namespaces.
With this configuration, the Nomad APM plugin must specify the job namespace when querying for information as the agent is configured with the wildcard.
Ref: https://github.com/hashicorp/nomad-autoscaler/issues/65#issuecomment-1620071860

nomad: specify namespace when querying group

---

plugins/builtin/strategy/threshold/plugin/plugin.go
plugins/builtin/strategy/threshold/plugin/plugin_test.go

The `lower_bound` value is always considered inclusive and the `upper_bound` value is always exclusive. This helps prevent overlapping or a dead zone when regions start or end right next to each other.
Also use `math.Inf` instead of `MaxFloat64` to allow a value that matches `MaxFloat64` to be considered within bounds.
No changelog since it doesn't change any user-facing behaviour.
Closes https://github.com/hashicorp/nomad-autoscaler/issues/727

threhsold: clarify the behaviour of bounds

---

CHANGELOG.md
policyeval/broker.go
policyeval/broker_test.go

When a policy is sent for evaluation by a handler, it is placed into the eval broker queue. If the queue already has an eval for the policy, it discards one of them, keeping the most recent one. This is used to guarantee that a policy is never processed in parallel by different workers.
The code had the `return` statement in the wrong scope, causing a duplicate eval to be enqueued even when the policy was already been processed, resulting in unexpected concurrent policy evaluations.
Closes https://github.com/hashicorp/nomad-autoscaler/issues/610

broker: prevent overlap of policy evaluations

---

CHANGELOG.md
policyeval/base_worker.go

Add `policy_id` and `target_name` labels to `scale.invoke.success_count` and `scale.invoke.error_count` metrics to help operators track policies that may be failing.
Closes https://github.com/hashicorp/nomad-autoscaler/issues/593

metrics: add `policy_id` and `target_name` labels to scale invoke

---

CHANGELOG.md
sdk/policy.go
sdk/policy_test.go

Return an error if a `check` is missing a `strategy` value to prevent panics.
Closes https://github.com/hashicorp/nomad-autoscaler/issues/611

policy: validate missing strategy

---

CHANGELOG.md
plugins/builtin/target/aws-asg/plugin/aws.go
plugins/builtin/target/aws-asg/plugin/plugin.go

When `scale_in_protection` is enabled, the AWS target plugin skips instances that are protected from scale in operations[1].
Closes #650 
[1] https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-instance-protection.html

aws: add `scale_in_protection` configuration

---

plugins/builtin/target/aws-asg/plugin/plugin.go
sdk/helper/scaleutils/cluster.go
sdk/helper/scaleutils/node_identifier.go

Add experimental configuration values to the AWS ASG plugin to allow cluster operators to bypass some of the safety checks enforced by the Autoscaler.
I'm still unsure about these changes, so I'm open to suggestions, but letting users experiment with them could generate useful information about the assumptions we make.
Ref: https://github.com/hashicorp/nomad-autoscaler/issues/672

aws: add experimental configuration

---

CHANGELOG.md
policyeval/base_worker.go

Autoscaler tries to scale even when dry-run is configured. This happens when the current count is out of the range of the configured min/max. Currently the dry-run check is performed after this checks are executed. https://github.com/hashicorp/nomad-autoscaler/blob/0d0ad24c2381f1c13995504a56354d0e9d269eeb/policyeval/base_worker.go#L146
This PR moves the dry-run check to inside the scaleTarget method so every scaling action goes through the check.

Fix autoscale when dry-run in set

---

CHANGELOG.md
plugins/builtin/strategy/target-value/plugin/plugin.go
plugins/builtin/strategy/target-value/plugin/plugin_test.go

Hey,
The two optional parameters max_scale_up and max_scale_down determine the maximum and minimum number of scaling differences between two evaluations.
It is useful to avoid scaling down or scaling up a job too quickly.
The code is not tested yet. For now, this is a draft pull request to see if you might be interested to include the feature in the target-value plugin.

accept max_scale_up and max_scale_down for target-value

---

policy/nomad/source_test.go

Once again CI didn't fully run in https://github.com/hashicorp/nomad-autoscaler/pull/844 so I didn't notice the failing test.

ci: fix `TestSource_canonicalizePolicy`

---

CHANGELOG.md
policy/file/parse.go
policy/file/parse_test.go
policy/file/test-fixtures/full-cluster-policy.hcl
policy/nomad/parser.go
policy/nomad/parser_test.go
policy/nomad/source.go
policy/nomad/source_test.go
policy/nomad/test-fixtures/full-scaling.json.golden
policy/nomad/test-fixtures/src/full-scaling.hcl
policyeval/base_worker.go
sdk/policy.go
sdk/policy_test.go

The Nomad Autoscaler uses the current time as the end of the query window. This can cause instability, specially for strategies that only take the most recent data point into account, because the latest data may still be processing.
`query_window_offset` defines a time offset applied to the query window to push it back in time. A short `query_window_offset` value can help with the unstable readings, and a long value can be used for predictive scaling based on historical data (for example, from `7d` ago).
Closes https://github.com/hashicorp/nomad-autoscaler/issues/843.

policy: add `query_window_offset` configuration

---

.github/workflows/build.yml

`macos-11` runner has been deprecated. Changing to generic `macos-latest` runner instead since we don't depend on any macos version specific tooling and just want darwin os.

build: use a generic mac runner

---

.github/workflows/build.yml
.github/workflows/ci.yaml
.github/workflows/copywrite.yml
.github/workflows/nightly-release.yml

Update HashiCorp actions
* hashicorp/actions-docker-build v1 ==> v2.0.0
* hashicorp/actions-generate-metadata v1 ==> v1.1.1
* hashicorp/actions-packaging-linux v1 ==> v1.8.0
* hashicorp/setup-copywrite v1.1.2 ==> v1.1.3
Updated actions
* actions/checkout v3.5.3 ==> v4.1.7
* actions/download-artifact v3.0.2 ==> v4.1.7
* actions/github-script v6.4.1 ==> v7.0.1
* actions/setup-go v4.0.1 ==> v5.0.1
* actions/upload-artifact v3.1.2 ==> v4.3.3
* eregon/publish-release v1.0.5 ==> v1.0.6
* ncipollo/release-action v1.12.0 ==> v1.14.0
* slackapi/slack-github-action v1.24.0 ==> v1.26.0

[actions] Update project's GitHub actions

---

CHANGELOG.md
policy/handler.go

Resolves `Incorrect conversion between integer types` alerts to catch potential overflows.

bug: fix integer type conversion

---

.github/workflows/build.yml
.github/workflows/ci.yaml
.github/workflows/copywrite.yml

The GitHub Actions configuration doesn't run CI on pull requests, only on pushes which doesn't cover external PRs (Ex https://github.com/hashicorp/nomad-autoscaler/pull/945). Update the behavior to match what we do in Nomad core, where PRs get CI as well as merges to main.

test: run CI on pull requests

---

CHANGELOG.md
go.mod
go.sum

Fixes: https://github.com/hashicorp/nomad-autoscaler/issues/944

deps: update Nomad API package to 1.8.3

---

CHANGELOG.md
sdk/helper/nomad/config.go

For #944 we fixed the Nomad API package so that it no longer mutated the private `url` field if previously set, which allowed reusing an `api.Config` object between clients when a unix domain socket was in use.
However, the autoscaler plugins for Nomad strategy and target don't use the `api.Config` object we parse directly and instead get a map of string->string derived from that config so it can be passed over the go-plugin interface. This mapping did not account for the `Address` field being mutated when unix domain sockets are in use, so the bug was not actually fixed.
Update the mapping to use the safe `URL()` method on the config, rather than reading the `Address` field.
Fixes: https://github.com/hashicorp/nomad-autoscaler/issues/955
Ref: https://github.com/hashicorp/nomad/pull/23785

config: use `URL` method to get Nomad address for plugins

---

Dockerfile
go.mod
plugins/test/noop-apm/go.mod
plugins/test/noop-strategy/go.mod
plugins/test/noop-target/go.mod

We updated to Go 1.24 in #1045 but it looks like this missed a few build components that are now causing issues with dependabot PRs.

build: update toolchain components to 1.24

---

CHANGELOG.md
go.mod
go.sum

Update the Nomad API package to the current tip of main so we can verify builds are green ahead of the Nomad 1.10.0 GA.

stage changes for Nomad 1.10 release

---

Dockerfile

Alpine 3.21 ships with busybox 1.37 which addresses CVE-2024-58251 and CVE-2025-46394.

build: update alpine to address busybox vulnerability

---

Dockerfile

The build pipeline's security scanner is picking up a (not meaningful) vuln in the Alpine base image we're using, which is preventing nightlies from being published. Rev the alpine base image.
Ref: https://github.com/hashicorp/crt-workflows-common/actions/runs/15543056919/job/43758419778
Fixes: https://github.com/hashicorp/nomad-autoscaler/issues/1097

build: bump alpine base image to 3.22

---

policy/file/source.go
policy/manager.go
policy/manager_test.go

This PR addresses 2 big bugs present on the policy tracking:
- When updating the file policy source, the internal map that holds the policies was only being populated with the policy name and file, but the content was missing, resulting on every file policy resolving to nil.
- The policy update messages where compared to all running handlers disregarding the source, which led to updates on one source deleting handlers for the others.

Tracking policies from different sources
